### ISSUE TITLE
[Regression]: Duration labels can rarely appear on incorrect thumbs

### ISSUE THREAD

**Issue by CyanVoxel** [TagStudioDev/TagStudio#1125]
### Checklist

- [x] I am using an up-to-date version.
- [x] I have read the [documentation](https://github.com/TagStudioDev/TagStudio/blob/main/docs/index.md).
- [x] I have searched existing [issues](https://github.com/TagStudioDev/TagStudio/issues).

### TagStudio Version

main branch (Alpha v9.5.5+)

### Operating System & Version

macOS 15.6.1

### Description

Regression of #1009 and possibly #965. Duration labels now have a chance to show in the incorrect files, for example these Keynote files:
<img width="1988" height="292" alt="Image" src="https://github.com/user-attachments/assets/7d7e100c-a6c5-4236-a914-2ae03e5717ef" />

I believe this is due to the removal of the timestamp check for updating item thumb labels in #1119, as that was the fix added in #1010. I didn't make a comment on it at the time because I was unable to reproduce the regression with the new layout, but (of course) as soon as it was pulled I encountered an edge case that reproduced it. Moving pages around causes the duration labels to reset.

### Expected Behavior

Item thumbnails should only show the information for the current entry representing them.

### Steps to Reproduce

(Difficult to reproduce reliably)
1. Be on a page that has files with duration labels on the top-most rows
2. With new non-audio/video files added to the library, refresh the page
3. That *may* cause the race condition that produces the bug

Alternatively, load a library that has several videos at the top of a long page and other file types further down. Scrolling quickly may reproduce the issue.

### Logs

N/A

**Comment by TheBobBobs** [comment]
I think this is caused by the change in this [commit](https://github.com/TagStudioDev/TagStudio/commit/8a4d4def072dd06433b7c60aef62aa49f518d731).
When updating an item thumb the loading icon has an empty Path. So checking that `filename != Path()` should fix this without breaking displaying file stems.

**Comment by CyanVoxel** [comment]
> I think this is caused by the change in this [commit](https://github.com/TagStudioDev/TagStudio/commit/8a4d4def072dd06433b7c60aef62aa49f518d731). When updating an item thumb the loading icon has an empty Path. So checking that `filename != Path()` should fix this without breaking displaying file stems.

I'm still able to reproduce the issue when reverting the changes in that commit:
<img width="570" height="285" alt="Image" src="https://github.com/user-attachments/assets/2fd17fe7-6e37-45dd-a1b8-d931c597eef2" />

And adding a `filename != Path()` does not seem to resolve the issue, at least inside the `set_extension()` method.

I believe this really is just a regression of the race condition in #1009 since it coincides with the removal of the timestamp cutoff check added in #1010 and removed in #1119 that prevented this issue.
