### ISSUE TITLE
Use of lambda functions when connecting to Qt signals

### ISSUE THREAD

**Issue by gabrieljreed** [TagStudioDev/TagStudio#131]
I've noticed that across the codebase, signals are connected using `lambda` functions. While they certainly work, and can seem like a good solution for properly connecting signals to functions (especially with arguments), they do have some downsides.

## Memory safety

Lambda functions can cause QWidgets to not be properly garbage collected. (See [this forum post](https://forum.qt.io/topic/92825/python-pyqt-qdialog-with-connect-lambda-leaks) and [this StackOverflow thread](https://stackoverflow.com/a/48501804). This can lead to some unexpected behavior and/or the application consuming more resources than expected.

## Code cleanliness/readability 

While it's true that 

```python
self.my_button.clicked.connect(lambda: self.my_button_pressed())
```

does work,

```python
self.my_button.clicked.connect(self.my_button_pressed)
```

is functionally equivalent, along with being cleaner and easier to read. Additionally, while lambda functions can be extremely useful in the right situations, they can over-complicate what would otherwise be a simple operation.

# Fix

Simple cases can just drop the lambda and actual function call in favor of a reference to the function. This is actually the intended way to use signals (see [this example](https://doc.qt.io/qtforpython-6/examples/example_widgets_tutorials_addressbook.html) from the Qt for Python docs).

Example:

```python
# Original
open_library_action.triggered.connect(lambda: self.open_library_from_dialog())

# Updated
open_library_action.triggered.connect(self.open_library_from_dialog)
```

More complicated cases (ex: a function needs to be called with specific arguments) can be replaced with `functools.partial`, which is part of the Python standard library. `partial` creates a "partial" function call, with pre-filled arguments.

Example:

```python
# Original
self.edit_modal.saved.connect(lambda: self.edit_tag_callback(btp))

# Updated
from functools import partial

self.edit_modal.saved.connect(partial(self.edit_tag_callback, btp))
```

**Comment by gabrieljreed** [comment]
I can start updating this, I just wanted to do my due diligence and submit an issue first.

**Comment by Loran425** [comment]
This seems like a solid improvement.
Great write up to explain the issue and the fix.

**Comment by seakrueger** [comment]
Hello, do you know of any updates on this? 
The two linked forum threads are from Qt5 (PyQt5 and pyside2 respectively) and causing a leak if a reference to self is passed to an external function via a lambda in .connect(). I have grepped the repo for any instance of this and could not find any. 
I went and checked Qt's bug tracker for this issue and found two relevant issues: 
1. [PYSIDE-2646](https://bugreports.qt.io/browse/PYSIDE-2646) for qt6.5 and its marked as resolved in 6.7 and 6.8. Running the provided test program shows it being properly GCed after closing on Pyside6.7.1 
2. [PYSIDE-2346](https://bugreports.qt.io/browse/PYSIDE-2346) for qt6.5 and was resolved in Qt6.6. I ran the provided leak example for ~7 minutes (90000 iterations) with no increase in memory usage, something that should have shown a leak in ~0.2 seconds (500 iterations) according to there example. 
It also seems that using partial does not guarantee safety from this gc issue, I found two relevant issues for it also, [PYSIDE-2371](https://bugreports.qt.io/browse/PYSIDE-2371) and [PYSIDE-2793](https://bugreports.qt.io/browse/PYSIDE-2793) which is still open and marked priority low. 

I do agree that lambda should not be used where its unnecessary. Personally, from a purely stylistic perspective, I'd prefer to keep using lambda, but if its a continued concern switching to partial is fine.

**Comment by VasigaranAndAngel** [comment]
i always think that using lambda could be risky if it relies on local variables. as changes to those variables might break it. so i'm a bit hesitant to use it. but now i realize it's not such a big deal. but i’m still not comfortable with using local variables in reusable lambda functions.
